spring.application.name=translogix-backend

server.port=8081

# =====================================================
# SQL SERVER
# =====================================================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=translogix_db;encrypt=true;trustServerCertificate=true

spring.datasource.username=VijayBalande01
spring.datasource.password=Vijay@12345

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# =====================================================
# JWT
# =====================================================

jwt.secret=TranslogixSuperSecretKeyForJwtAuthentication2026VerySecureKey123456789

jwt.expiration=86400000