spring.application.name=translogix-backend

server.port=${PORT:8081}

# =====================================================
# POSTGRESQL
# =====================================================

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =====================================================
# JWT
# =====================================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# =====================================================
# LOGGING
# =====================================================

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO